name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck-action
        # You may pin to the exact commit or the version.
        # uses: deep5050/cppcheck-action@23477d13f5940d7911ae7d533d368033a58a099a
        uses: deep5050/cppcheck-action@v2.0.0